# Learning Numpy

In [1]:
import numpy as np

**Creation of numpy array using list**

In [2]:
myarr = np.array([1,2,3,4])

In [3]:
myarr

array([1, 2, 3, 4])

In [4]:
myarr[0]

1

In [5]:
myarr.shape

(4,)

In [6]:
myarr.dtype

dtype('int64')

In [7]:
myarr1 = np.array([[2,32,72,8,9]],np.int32)

In [8]:
myarr1

array([[ 2, 32, 72,  8,  9]], dtype=int32)

In [9]:
myarr1[0,1]

32

In [10]:
myarr1.shape

(1, 5)

In [11]:
myarr1.dtype

dtype('int32')

In [12]:
myarr1[0,1]=45

In [13]:
myarr1

array([[ 2, 45, 72,  8,  9]], dtype=int32)

**Array Creation**

**Conversion from other python structures**

In [14]:
listarray = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [15]:
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
listarray.shape

(3, 3)

In [17]:
listarray.size

9

In [18]:
np.array({22,32,11,10})

array({32, 10, 11, 22}, dtype=object)

**Intrinsic numpy array creation**

In [19]:
zeros = np.zeros((2,5))

In [20]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [21]:
rng = np.arange(15)

In [22]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [23]:
lspace = np.linspace(1,50,5)

In [24]:
lspace

array([ 1.  , 13.25, 25.5 , 37.75, 50.  ])

In [25]:
emp = np.empty((4,5))

In [26]:
emp

array([[6.89924254e-310, 4.66722297e-310, 6.89924106e-310,
        6.89924205e-310, 6.89924106e-310],
       [6.89924205e-310, 6.89924205e-310, 6.89924258e-310,
        6.89924105e-310, 6.89924205e-310],
       [6.89924105e-310, 6.89924167e-310, 6.89924112e-310,
        6.89924259e-310, 6.89924207e-310],
       [6.89924205e-310, 6.89924259e-310, 6.89924196e-310,
        6.89924259e-310, 6.89924196e-310]])

In [27]:
emp_like = np.empty_like(lspace)

In [28]:
emp_like

array([ 1.  , 13.25, 25.5 , 37.75, 50.  ])

In [29]:
ide = np.identity(5)

In [30]:
ide

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [31]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [32]:
arr = np.arange(99)

In [33]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [34]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [35]:
arr = arr.reshape(3,33)

In [36]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [37]:
arr = arr.ravel()

In [38]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

**Numpy Axis**

In [39]:
x = [[1,2,3],[4,5,6],[7,1,0]]

In [40]:
ar = np.array(x)

In [41]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [42]:
ar.sum(axis=0)

array([12,  8,  9])

In [43]:
ar.sum(axis=1)

array([ 6, 15,  8])

In [44]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [45]:
ar.T.sum(axis=0)

array([ 6, 15,  8])

In [46]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [47]:
ar.flat

In [48]:
for i in ar.flat:
    print(i)

1
2
3
4
5
6
7
1
0


In [49]:
ar.ndim

2

In [50]:
ar.size

9

In [51]:
ar.nbytes

72

In [52]:
ar.dtype

dtype('int64')

**various methods in array**

In [53]:
one=np.array([1,3,4,634,2])

In [54]:
one.argmax()

3

In [55]:
one.argmin()

0

In [56]:
one.argsort()

array([0, 4, 1, 2, 3])

In [57]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [58]:
ar.argmin()

8

In [59]:
ar.argmax()

6

In [60]:
ar.argmax(axis=0)

array([2, 1, 1])

In [61]:
ar.argmax(axis=1)

array([2, 2, 0])

In [62]:
ar.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]])

In [63]:
ar.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]])

In [64]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]])

In [65]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [66]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [67]:
y=[[1,2,1],[4,0,6],[8,1,0]]

In [68]:
ar1=np.array(y)

In [69]:
ar1

array([[1, 2, 1],
       [4, 0, 6],
       [8, 1, 0]])

In [70]:
y

[[1, 2, 1], [4, 0, 6], [8, 1, 0]]

In [71]:
ar1+ar

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

In [72]:
ar1*ar

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  1,  0]])

In [73]:
arr1=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [74]:
arr2=np.array([[1,2,1],[5,4,6],[8,4,5]])

In [75]:
arr1*arr2

array([[ 1,  4,  3],
       [20, 20, 36],
       [56, 32, 45]])

In [76]:
np.dot(arr1,arr2)

array([[ 35,  22,  28],
       [ 77,  52,  64],
       [119,  82, 100]])

In [77]:
np.outer([1,2,3],[4,5,6])

array([[ 4,  5,  6],
       [ 8, 10, 12],
       [12, 15, 18]])

In [78]:
ar.max()

7

In [79]:
ar.min()

0

In [80]:
ar.sum()

29

In [81]:
np.where(ar>5)

(array([1, 2]), array([2, 0]))

In [82]:
np.count_nonzero(ar)

8

In [83]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1]))

In [84]:
arr=np.array([1,2,3,4,5,6])

In [85]:
arr

array([1, 2, 3, 4, 5, 6])

In [86]:
arr.mean()

3.5

In [87]:
np.median(arr)

3.5

**Checking data size for numpy**

In [88]:
import sys

In [89]:
py_ar=[0,4,55,2]

In [90]:
np_ar = np.array(py_ar)

In [91]:
sys.getsizeof(1)*len(py_ar)

112

In [92]:
np_ar.itemsize * np_ar.size

32

In [93]:
np_ar.size

4

In [94]:
np_ar.shape

(4,)